import Head from "next/head";
import styles from "../styles/Home.module.css";

import ImageProfile from "../components/ImageProfile";
import Navbar from "../components/Navbar";
import Section from "../components/Section";

import { DiAndroid, DiCode, DiPhotoshop } from "react-icons/di";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex flex-col">
        <ImageProfile></ImageProfile>

        <div className="bg-back flex flex-col text-center ">
          <div id="pageIndex" className="">
            <div className="relative top-[-50px] z-10 flex justify-center">
              <h1 className="text-white text-5xl font-extrabold w-[80vw] rounded-t-full bg-back pt-14">
                Leandro
                <br />
                Rocha
              </h1>
            </div>
          </div>
          <Section id="Index" subTitle="Programmer">
            <>
              <p>
                Hello! I am Web Developer from United States, New York. I have
                rich experience in web site design and building, also I am good
                at wordpress. I love to talk with you about our unique.
              </p>
              <p className="text-center lg:text-left">
                <a className="button mt-4 " href="http://">
                  Entre em Contato
                </a>
              </p>
            </>
          </Section>

          <Section title="Sobre" id="About" subTitle="MY STORY">
            <>
              <p>
                Pellentesque posuere. Praesent turpis. Aenean posuere, tortor
                sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin
                urna dolor sagittis lacus. Pellentesque posuere. Praesent
                turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue
                blandit nunc, eu sollicitudin urna dolor sagittis lacus.
              </p>
              <p>
                Pellentesque posuere. Praesent turpis. Aenean posuere, tortor
                sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin
                urna dolor sagittis lacus. Donec elit libero, sodales nec,
                volutpat a, suscipit non, turpis.
              </p>
            </>
          </Section>
          <Section title="Serviços" id="Services" subTitle="O que eu faço">
            <>
              <div className="grid gap-16 grid-cols-1 md:grid-cols-2 lg:grid-cols-4">
                <div>
                  <div className="icon">
                    <DiCode />
                  </div>
                  <h4>Web Development</h4>
                  <p>
                    The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
                <div>
                  <div className="icon">
                    <DiAndroid />
                  </div>
                  <h4>App Development</h4>
                  <p>
                    The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
                <div>
                  <div className="icon">
                    <DiPhotoshop />
                  </div>
                  <h4>Web Design</h4>
                  <p>
                    a The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
              </div>
            </>
          </Section>
          <Section title="Experiencia" id="Experience">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Skills" id="Skills">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Portfolio" id="Portfolio">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Contato" id="Contact">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <footer></footer>
        </div>
      </main>
    </div>
  );
}
