import Head from "next/head";
import styles from "../styles/Home.module.css";

import ImageProfile from "../components/ImageProfile";
import Navbar from "../components/Navbar";
import Section from "../components/Section";
import SubTitle from "../components/SubTitle";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex flex-col">
        <ImageProfile></ImageProfile>

        <div className="bg-back flex flex-col text-center ">
          <div id="pageIndex" className="border-b border-second pb-8">
            <div className="relative top-[-50px] z-10 flex justify-center">
              <h1 className="text-white text-5xl font-extrabold w-[80vw] rounded-t-full bg-back pt-14">
                Leandro
                <br />
                Rocha
              </h1>
            </div>
            <SubTitle subTitle="Programmer"></SubTitle>

            <p>Texto</p>
            <a className="button" href="http://">
              Entre em Contato
            </a>
          </div>
          <Section title="Sobre" id="About">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Serviços" id="Services">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Experiencia" id="Experience">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Skills" id="Skills">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Portfolio" id="Portfolio">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Contato" id="Contact">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <footer></footer>
        </div>
      </main>
    </div>
  );
}
