import Head from "next/head";
import styles from "../styles/Home.module.css";

import ImageProfile from "../components/ImageProfile";
import Navbar from "../components/Navbar";
import Section from "../components/Section";
import SubTitle from "../components/SubTitle";
import Button from "../components/Button";

import { DiAndroid, DiCode, DiPhotoshop } from "react-icons/di";
import { BiMailSend } from "react-icons/bi";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex flex-col ">
       

        <div className="bg-back ">
          <div id="pageIndex" className="lg:h-screen text-center flex flex-col lg:flex-row items-center">
            <ImageProfile></ImageProfile>
            <div className="lg:w-1/2 mt-10">
             <div className="relative top-[-50px] z-10 flex justify-center">
              <h1 className="text-white text-5xl font-extrabold w-[80vw] rounded-t-full bg-back pt-14">
                Leandro
                <br />
                Rocha
              </h1>
            </div>
            <Section id="Index" subTitle="Programmer">
              <>
                <p>
                  Hello! I am Web Developer from United States, New York. I have
                  rich experience in web site design and building, also I am good
                  at wordpress. I love to talk with you about our unique.
                </p>
                <p className="text-center lg:text-left">
                  <Button click={()=> {}} title="Entre em Contato"></Button>
                </p>
              </>
            </Section>
         
            </div>
          </div>
          

          <Section title="Sobre" id="About" subTitle="MY STORY">
            <>
              <p>
                Pellentesque posuere. Praesent turpis. Aenean posuere, tortor
                sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin
                urna dolor sagittis lacus. Pellentesque posuere. Praesent
                turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue
                blandit nunc, eu sollicitudin urna dolor sagittis lacus.
              </p>
              <p>
                Pellentesque posuere. Praesent turpis. Aenean posuere, tortor
                sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin
                urna dolor sagittis lacus. Donec elit libero, sodales nec,
                volutpat a, suscipit non, turpis.
              </p>
              <div className="grid gap-x-16 gap-y-1 grid-cols-1 md:grid-cols-4 lg:grid-cols-8">
                <SubTitle subTitle={"Age"}></SubTitle>
                <span className="col-span-3">32</span>

                <SubTitle subTitle={"ADDRESS"}></SubTitle>
                <span className="col-span-3">
                  Formiga - Minas Gerais - Brasil
                </span>

                <SubTitle subTitle={"Email"}></SubTitle>
                <span className="col-span-3">
                  <a href="mailto:leandrorochaoliveira@icloud.com">
                    leandrorochaoliveira@icloud.com
                  </a>
                </span>

                <SubTitle subTitle={"Phone"}></SubTitle>
                <span className="col-span-3">
                  <a href="tel:+5537999110817">(37) 9 9911-0817</a>
                </span>
              </div>
            </>
          </Section>
          <Section title="Serviços" id="Services" subTitle="O que eu faço">
            <>
              <div className="grid gap-16 grid-cols-1 md:grid-cols-2 lg:grid-cols-4">
                <div>
                  <div className="icon">
                    <DiCode />
                  </div>
                  <h4>Web Development</h4>
                  <p>
                    The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
                <div>
                  <div className="icon">
                    <DiAndroid />
                  </div>
                  <h4>App Development</h4>
                  <p>
                    The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
                <div>
                  <div className="icon">
                    <DiPhotoshop />
                  </div>
                  <h4>Web Design</h4>
                  <p>
                    a The web development process includes: web design, web
                    content, client-side / server-side scripting and network
                    security configuration.
                  </p>
                </div>
              </div>
            </>
          </Section>
          <Section title="Experiencia" id="Experience" subTitle="WORKING WITH">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Skills" id="Skills">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Portfolio" id="Portfolio">
            <>
              <p>paragrafo 1</p>
              <p>paragrafo 2</p>
            </>
          </Section>
          <Section title="Contato" id="Contact" subTitle="LET'S TALK">
            <div className="grid gap-8 grid-cols-2">
              <div>
                <div className="mb-6">
                  <label
                    htmlFor="large-input"
                    className="block mb-2 ml-6 text-sm font-medium text-gray-900 dark:text-white"
                  >
                    Nome
                  </label>
                  <input
                    type="text"
                    id="large-input"
                    placeholder="Your contact name"
                    className="block w-full p-4 text-white text-sm  outline-none border border-[#585d65] rounded-3xl bg-back sm:text-md focus:ring-white focus:border-white"
                  />
                </div>

                <div className="mb-6">
                  <label
                    htmlFor="large-input"
                    className="block mb-2 ml-6 text-sm font-medium text-gray-900 dark:text-white"
                  >
                    E-mail
                  </label>
                  <input
                    type="text"
                    id="large-input"
                    placeholder="example@domain.com"
                    className="block w-full p-4 text-white text-sm  outline-none border border-[#585d65] rounded-3xl bg-back sm:text-md focus:ring-white focus:border-white"
                  />
                </div>

                <div className="mb-6">
                  <label
                    htmlFor="message"
                    className="block mb-2 ml-6 text-sm font-medium text-gray-900 dark:text-white"
                  >
                    Your message
                  </label>
                  <textarea
                    id="message"
                    rows={4}
                    className="block p-3 w-full text-sm outline-none text-white rounded-3xl border  border-[#585d65]  bg-back sm:text-md focus:ring-white focus:border-white"
                    placeholder="To Write"
                  ></textarea>
                </div>

                <div>
                  <Button click={()=> {}} title="Send Message"><BiMailSend className="" /></Button>
                </div>
              </div>
              <div className="rounded-3xl py-16 px-8 border  border-[#585d65] ">
                <div className="grid gap-x-16 gap-y-1 grid-cols-4">
                  <SubTitle subTitle={"Age"}></SubTitle>
                  <span className="col-span-3">32</span>

                  <SubTitle subTitle={"ADDRESS"}></SubTitle>
                  <span className="col-span-3">
                    Formiga - Minas Gerais - Brasil
                  </span>

                  <SubTitle subTitle={"Email"}></SubTitle>
                  <span className="col-span-3">
                    <a href="mailto:leandrorochaoliveira@icloud.com">
                      leandrorochaoliveira@icloud.com
                    </a>
                  </span>

                  <SubTitle subTitle={"Phone"}></SubTitle>
                  <span className="col-span-3">
                    <a href="tel:+5537999110817">(37) 9 9911-0817</a>
                  </span>
                </div>
              </div>
            </div>
          </Section>
          <footer></footer>
        </div>
      </main>
    </div>
  );
}
